x-service-templates:
  app: &appImage
    image: dbiagi/rinha-de-backend-2025-go:latest
    command: ["/app/bin/app", "serve"]
    environment:
      PORT: 9999
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: rinha2025
      DB_PASSWORD: 123456
      DB_NAME: rinha2025
      PROCESSOR_DEFAULT_HOST: "payment-processor-default:8080"
      PROCESSOR_FALLBACK_HOST: "payment-processor-fallback:8080"
      PROCESSOR_MAX_RESPONSE_TIME: 100
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
    networks:
      - default
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy


services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-1
      - app-2
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: rinha2025
      POSTGRES_DB: rinha2025
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha2025 -d rinha2025"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "130MB"
  app-1:
    <<: *appImage
  app-2:
    <<: *appImage
  worker:
    <<: *appImage
    command: ["/app/bin/app", "worker"]
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "5MB"
networks:
  default:
    driver: bridge
  payment-processor:
    external: true
